### ISSUE TITLE
Is still being developed/maintained?

### ISSUE THREAD

**Issue by svenstaro** [p12tic/libsimdpp#27]
I was looking into using this but the lack of activity is unsettling as I'd like to know that if I find bugs and such that they are resolved and that the library keeps improving with new instruction sets.

**Comment by p12tic** [comment]
Hi,

The library will be maintained for the foreseeable future. The lack of activity was caused by hardware failure which resulted in inability to run full test suite on all different compilers and architectures. Since any change may cause failures that are hard to foresee, no new changes were pushed in order not to make matters worse.

As of now, the testing rig is running again so there will definitely be more activity. You can check out  several tens of commits I've just pushed to the repository.
