### ISSUE TITLE
SSE2 implementation of i_to_float32(const uint32<4>& a) could be more efficient

### ISSUE THREAD

**Issue by peabody-korg** [p12tic/libsimdpp#82]
the conditional div/2, conv, mul*2 looks less efficient and is less accurate than the bias, conv, bias method:

```
float conv(uint32_t a)
{
    return (float)((int32_t)(a - 0x80000000)) + (float)0x80000000;
}
```
A similar method can be used to reverse this for converting float->uint32_t, with an additional trunc() step to properly truncate towards 0 and not 0x80000000.

**Comment by p12tic** [comment]
Thanks for the ideas. Unfortunately in the case of uint32 -> float32 conversion, a simple bias can not be used, because the values around zero will become so large that float32 can not represent them in sufficient precision. However, using bias instead of multiplication is still more efficient, I've applied a fix in de9ae6c8d72c9ba8857ebcc9dc37651d19fe0b5f (explained in cfba73a391a9c03f0c6cb7a6cdfb754e53cfa4ba). Do you have any ideas how this could be improved more?

Similarly, float32->uint32 conversion can't be implemented with a simple bias->conv->bias step. An implementation using conditional bias has been added in b38a1c278af969fedf1fe45a6031e826dfae1f1d.

**Comment by peabody-korg** [comment]
how'd I miss the precision issue!?! derp! thanks for point that out. your biasing solution is clever. I'll see if I can think of anything else to try. I wonder whether the cmp_gt(a, 0x7fffffff) might be improved with cmp_lt(to_int32(a),0)? Compiler optimization might do that anyway (haven't checked), but if not, generating a vector full of zeros is presumably more efficient than generating a vector full of 0x7fffffff.

**Comment by peabody-korg** [comment]
Should't uint32x4 <-> float32x4 use _mm_cvtepu32_ps() and _mm_cvtps_epu32() for AVX512?

**Comment by peabody-korg** [comment]
this:
    float32<4> f_large = add(f_a, 0x100000000);
    return blend(f_large, f_a, is_large);

might be more efficient as:
    return add(f_a, bit_and(is_large, float(0x100000000)));

**Comment by p12tic** [comment]
Yeah, I agree. This very elegantly removes the need to use blend, which is not available as an instruction everywhere. Could you maybe do a PR with this fix for both SSE2 and AVX2?

As for _mm_cvtepu32_ps(), I was confused by Intel instruction guide not listing the intrinsic at all, even for AVX512VL. Even though libsimdpp does not support AVX512VL yet, we could add an implementation using correct functions already.

**Comment by peabody-korg** [comment]
I'm referring to https://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-software-developer-instruction-set-reference-manual-325383.pdf. _mm_cvtepu32_ps() appears in the VCVTUDQ2PS instruction description, and appears to be supported for both AVX512VL and AVX512F.

**Comment by p12tic** [comment]
Sorry, I didn't explain myself well enough. [This reference](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#expand=659,1532&text=cvtepu32_) does not list _mm_cvtepu32_ps() which confused me. It is documented in other resources and is present in headers, so we should use it.
